config/routes.rb
Rails.application.routes.draw do
  match "/404", via: :all, to: "errors#not_found"
  match "/500", via: :all, to: "errors#internal_server_error"

  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  get "telegram_auth", to: "telegram#telegram_auth"
  post "telegram_auth", to: "telegram#telegram_auth"
  post "telegram/send_reminder/:id", to: "telegram#send_reminder", as: :send_reminder
  # works same as above
  # post "telegram/:id/send_reminder", to: "telegram#send_reminder", as: :send_reminder

  root "static_public#landing_page"
  get "about", to: "static_public#about"
  get "pricing", to: "static_public#pricing"
  get "privacy", to: "static_public#privacy"
  get "terms", to: "static_public#terms"

  authenticated :user, lambda { |u| u.superadmin? } do
    scope :superadmin, as: "superadmin" do
      root "superadmin#users"
      get "tenants", to: "superadmin#tenants"
      get "users", to: "superadmin#users"
    end
  end

  resources :users, only: [:show] do
    member do
      patch :resend_invitation
    end
  end

  resources :tenants do
    member do
      patch :switch
    end
  end

  # stripe
  post "checkout", to: "checkout#create"
  get "checkout/success", to: "checkout#success"
  get "checkout/failure", to: "checkout#failure"
  post "billing_portal", to: "billing_portal#create"
  post "webhooks", to: "webhooks#create"

  resources :members, except: [:create, :new] do
    get :invite, on: :collection
  end

  get "dashboard", to: "tenant#dashboard"
  get "calendar", to: "tenant#calendar"
  get "activity", to: "tenant#activity"
  get "charts", to: "tenant#charts"
  get "tasks_report", to: "tenant#tasks_report"

  resources :clients do
    resources :comments
  end
  resources :payments
  resources :tasks do
    member do
      patch :change_status
    end
    resources :comments
  end
  resources :projects do
    member do
      patch :change_status
    end
  end
  resources :tags
  resources :cash_accounts
end

app/models/task.rb
class Task < ApplicationRecord
  acts_as_tenant(:tenant)
  belongs_to :project, counter_cache: true
  belongs_to :member, counter_cache: true
  belongs_to :creator, class_name: "Member", foreign_key: :creator_id
  has_many :taggings, as: :taggable, dependent: :destroy
  has_many :tags, through: :taggings
  has_many :comments, as: :commentable, dependent: :destroy

  validates :name, :status, presence: true

  scope :planned, -> { where(status: "planned") }
  scope :progress, -> { where(status: "progress") }
  scope :done, -> { where(status: "done") }
  scope :mine, -> { where(member: current_user.member) }
  scope :overdue, -> { where(status: "done").where("deadline < ?", Time.zone.now) }  

  def to_s
    name
  end

  STATUSES = [:planned, :progress, :done]
  def self.statuses
    STATUSES.map { |status| [status, status] }
  end

  # for calendar
  def calendar_date
    if done_at.present?
      done_at
    elsif deadline.present?
      deadline
    else
      created_at
    end
  end

  # for calendar
  def status_color
    if status == "planned"
      "danger"
    elsif status == "progress"
      "warning"
    elsif status == "done"
      "success"
    else
      "danger"
    end
  end
  
  include PublicActivity::Model
  tracked owner: proc { |controller, model| controller.current_user }
  tracked tenant_id: proc { ActsAsTenant.current_tenant.id }
  # has_many :activities, as: :trackable, class_name: 'PublicActivity::Activity', dependent: :destroy
  has_many :activities, as: :trackable, class_name: 'PublicActivity::Activity'

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  include SetTenant # include ON TOP of controller that has to be scoped
  include RequireTenant # no current_tenant = no access to entire controller. redirect to root
  include SetCurrentMember # for role-based authorization. @current_member.admin?
  include RequireActiveSubscription # no access unless tenant has an active subscription

  before_action :set_task, only: %w[show edit update destroy change_status]

  def index
    @q = Task.ransack(params[:q])
    @pagy, @tasks = pagy(@q.result.includes(:member, :project, :creator, :tags).order("tasks.created_at DESC"))
  end

  def change_status
    if params[:status].present? && Task::STATUSES.include?(params[:status].to_sym)
      @task.update(status: params[:status])
    end
    if @task.status == "done"
      @task.update(done_at: Time.now)
    end
    @task.create_activity :update, parameters: {status: @task.status}

    text = "#{url_for controller: "tasks", action: "show"} status: #{@task.status}"
    TelegramMailer.group_message(text).deliver_now
    TelegramMailer.private_message(text, current_user).deliver_now
    redirect_to @task, notice: "Status updated to #{@task.status}"
  end

  def show
    @commentable = @task
    @comment = Comment.new
    #@activities = PublicActivity::Activity.includes(:trackable).order("created_at DESC").where(trackable_type: "Task", trackable_id: @task).all
    #@activities = PublicActivity::Activity.order("created_at DESC").where(trackable: @task)
    #@activities = PublicActivity::Activity.includes(:trackable).order("created_at DESC").where(trackable: @task)
    @activities = @task.activities.order("created_at DESC")
  end

  def new
    @task = Task.new
  end

  def edit
  end

  def create
    @task = Task.new(task_params)
    @task.creator_id = @current_member.id
    if @task.save
      redirect_to @task, notice: 'Task was successfully created.'
    else
      render :new
    end
  end

  def update
    Task.public_activity_off
    if @task.update(task_params)
      Task.public_activity_on
      @task.create_activity :update, parameters: {
        project: @task.project.to_s,
        name: @task.name,
        member: @task.member.to_s,
        creator: @task.creator.to_s,
        urgent: @task.urgent,
        status: @task.status,
        deadline: @task.deadline,
        done_at: @task.done_at,
        duration: @task.duration_minutes,
        description: @task.description
        }
      #@task.create_activity :update, parameters: {duration: @task.duration_minutes}
      redirect_to @task, notice: 'Task was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @task.destroy
    redirect_to tasks_url, notice: 'Task was successfully destroyed.'
  end

  private
    def set_task
      @task = Task.find(params[:id])
    end

    def task_params
      params.require(:task).permit(:project_id, :name, :description, 
        :deadline, :urgent, :status, :done_at, :member_id, :duration_minutes, tag_ids: [])
    end
end

app/views/tasks/_form.html.erb
<%= simple_form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <ul class="text-danger">
      <% @task.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  <% end %>

  <div class="form-inputs">
    <%= f.association :project %>
    <%= f.association :member %>
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :deadline, as: :date, html5: true %>
    <%= f.input :urgent %>
    <%= f.input :status, collection: Task.statuses, include_blank: false %>
    <%= f.input :done_at, as: :date, html5: true %>
    <%= f.input :duration_minutes %>
    <%= f.label :tags %>
    <%= f.select :tag_ids, Tag.where(category: "task").pluck(:name, :id), {}, { multiple: true, class: "selectize" } %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<% model_class = Task %>
<div class="card shadow">
  <div class="card-header">
    <h4>
      <%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %>
      Task
    </h4>
  </div>
  <div class="card-body">
    <%= render 'form', task: @task %>
  </div>
  <div class="card-footer">
    <%= link_to t(".back", default: t("helpers.links.back")).capitalize, @task, class: "btn btn-sm btn-secondary" %>
  </div>
</div>

app/views/tasks/index.html.erb
<% model_class = Task %>
<h3>
  <div class="text-center">
    Tasks
    <div class="badge bg-info">
      <%= @tasks.count %>
    </div>
    <%= link_to t('.new', default: t("helpers.links.new")), new_task_path, class: 'btn btn-primary' %>
    <!-- Button trigger modal -->
    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
      <i class="fa fa-search"></i>
      Search
    </button>
    <% if params.has_key?(:q) %>
      <%= link_to "Unfilter", tasks_path, class: "btn btn-secondary" %>
    <% end %>
  </div>
</h3>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Search</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <%= search_form_for @q, url: tasks_path do |f| %>
          <%= model_class.human_attribute_name(:client) %>
          <%= f.select :project_client_name_cont, Client.all.map{|c| [c.name, c.name]}, {include_blank: Client.all.length > 1}, class: 'selectize' %>
          <%= model_class.human_attribute_name(:creator) %>
          <%= f.select :creator_user_email_cont, Member.all.map{|c| [c.user.email, c.user.email]}, {include_blank: Member.all.length > 1}, class: 'selectize' %>
          <%= model_class.human_attribute_name(:project) %>
          <%= f.select :project_name_cont, Project.all.map{|c| [c.name, c.name]}, {include_blank: Project.all.length > 1}, class: 'selectize' %>
          <%= model_class.human_attribute_name(:member) %>
          <%= f.select :member_user_email_cont, Member.all.map{|c| [c.user.email, c.user.email]}, {include_blank: Member.all.length > 1}, class: 'selectize' %>
          <%= model_class.human_attribute_name(:name) %>
          <%= f.search_field :name_cont, class: "form-control" %>
          <%= model_class.human_attribute_name(:status) %>
          <%= f.select :status_eq, Task.statuses, {:include_blank => true}, :class => "form-control" %>
          <br>
          <%= f.button :submit, class: "btn btn-primary btn-block" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<hr>
<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover table-sm table-light shadow">
    <thead>
      <tr>
        <th><%= sort_link(@q, :id) %></th>
        <th><%= sort_link(@q, :creator_user_email) %></th>
        <th><%= sort_link(@q, :project_name) %></th>
        <th><%= sort_link(@q, :member_user_email) %></th>
        <th><%= sort_link(@q, :name) %></th>
        <th><%= sort_link(@q, :description) %></th>
        <th><%= sort_link(@q, :deadline) %></th>
        <th><%= sort_link(@q, :urgent) %></th>
        <th><%= sort_link(@q, :status) %></th>
        <th><%= sort_link(@q, :done_at) %></th>
        <th><%= sort_link(@q, :duration_minutes) %></th>
        <th><%= model_class.human_attribute_name(:tags) %></th>
        <th><%= model_class.human_attribute_name(:actions) %></th>
      </tr>
    </thead>
    <tbody>
      <% @tasks.each do |task| %>
        <%= content_tag :tr, id: dom_id(task), class: dom_class(task) do %>
          <td><%= link_to task.id, task %></td>
          <td><%= link_to task.creator, task.creator %></td>
          <td><%= link_to task.project, task.project %></td>
          <td><%= link_to task.member, task.member %></td>
          <td><%= task.name %></td>
          <td><%= task.description %></td>
          <td><%= task.deadline %></td>
          <td><%= boolean_label(task.urgent) %></td>
          <td><%= status_label(task.status) %></td>
          <td><%= task.done_at %></td>
          <td><%= time_conversion(task.duration_minutes) %></td>
          <td><%= render 'tags/tags', model: task %></td>
          <td>
            <%= link_to t(".edit", default: t("helpers.links.edit")).capitalize, edit_task_path(task), class: 'btn btn-sm btn-warning' %>
            <%= link_to t(".destroy", default: t("helpers.links.destroy")).capitalize, task, method: :delete, data: { confirm: t('.confirm', default: t("helpers.links.confirm", default: 'Are you sure?')) }, class: 'btn btn-sm btn-danger' %>
          </td>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>
<br>
<%== pagy_bootstrap_nav(@pagy) %>

app/views/tasks/new.html.erb
<% model_class = Task %>
<div class="card shadow">
  <div class="card-header">
    <h4>
      <%=t '.title', :default => [:'helpers.titles.new', 'Create %{model}'], :model => model_class.model_name.human.titleize %>
      Task
    </h4>
  </div>
  <div class="card-body">
    <%= render 'form', task: @task %>
  </div>
  <div class="card-footer">
    <%= link_to t(".back", default: t("helpers.links.back")).capitalize, tasks_path, class: "btn btn-sm btn-secondary" %>
  </div>
</div>

app/views/tasks/show.html.erb
<% model_class = Task %>
<div class="card shadow">
  <div class="card-header">
    <h4>
      Task
    </h4>
  </div>
  <div class="card-body">

    <b>Project:</b>
    <%= link_to @task.project, @task.project %>
    <br>
  
    <b>Name:</b>
    <%= @task.name %>
    <br>

    <b>Member:</b>
    <%= link_to @task.member, @task.member %>
    <br>
  
    <b>Creator:</b>
    <%= link_to @task.creator, @task.creator %>
    <br>
  
    <b>Urgent:</b>
    <%= boolean_label(@task.urgent) %>
    <br>
  
    <b>Status:</b>
    <%= status_label(@task.status) %>
    <br>
  
    <b>Deadline:</b>
    <%= @task.deadline %>
    <br>

    <b>Done At:</b>
    <%= @task.done_at %>
    <br>

    <b>Duration:</b>
    <%= time_conversion(@task.duration_minutes) %>
    <br>

    <b>Tags:</b>
    <%= render 'tags/tags', model: @task %>
    <br>

    <b>Description:</b>
    <%= simple_format(@task.description) %>
  
  </div>
  <div class="card-footer">
    <div class="btn-group">
      <% Task::STATUSES.each do |status| %>
        <%= link_to change_status_task_path(@task, status: status), method: :patch, class: "btn btn-sm btn-info #{'disabled' if @task.status.to_sym == status}" do %>
          <%= status %>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="card-footer">
    <%= link_to t(".edit", default: t("helpers.links.edit")).capitalize, edit_task_path(@task), class: "btn btn-sm btn-warning" %>
    <%= link_to t(".destroy", default: t("helpers.links.destroy")).capitalize, @task, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-danger" %>
    <%= link_to t(".back", default: t("helpers.links.back")).capitalize, tasks_path, class: "btn btn-sm btn-secondary" %>
    <%= link_to send_reminder_path(@task), method: :post, class: "btn btn-sm btn-info" do %>
      <i class="fab fa-telegram-plane"></i>
      Send Reminder
    <% end %>
  </div>
  <div class="card-footer">
    <%= link_to "New Comment", new_task_comment_path(@commentable, @comment), class: "btn btn-sm btn-primary" %>
  </div>
</div>

<br>
<%= render partial: "comments/index", locals: {commentable: @commentable} %>

<%= render "tenant/activities" %>