config/routes.rb
Rails.application.routes.draw do
  match "/404", via: :all, to: "errors#not_found"
  match "/500", via: :all, to: "errors#internal_server_error"

  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  get "telegram_auth", to: "telegram#telegram_auth"
  post "telegram_auth", to: "telegram#telegram_auth"
  post "telegram/send_reminder/:id", to: "telegram#send_reminder", as: :send_reminder
  # works same as above
  # post "telegram/:id/send_reminder", to: "telegram#send_reminder", as: :send_reminder

  root "static_public#landing_page"
  get "about", to: "static_public#about"
  get "pricing", to: "static_public#pricing"
  get "privacy", to: "static_public#privacy"
  get "terms", to: "static_public#terms"

  authenticated :user, lambda { |u| u.superadmin? } do
    scope :superadmin, as: "superadmin" do
      root "superadmin#users"
      get "tenants", to: "superadmin#tenants"
      get "users", to: "superadmin#users"
    end
  end

  resources :users, only: [:show] do
    member do
      patch :resend_invitation
    end
  end

  resources :tenants do
    member do
      patch :switch
    end
  end

  # stripe
  post "checkout", to: "checkout#create"
  get "checkout/success", to: "checkout#success"
  get "checkout/failure", to: "checkout#failure"
  post "billing_portal", to: "billing_portal#create"
  post "webhooks", to: "webhooks#create"

  resources :members, except: [:create, :new] do
    get :invite, on: :collection
  end

  get "dashboard", to: "tenant#dashboard"
  get "calendar", to: "tenant#calendar"
  get "activity", to: "tenant#activity"
  get "charts", to: "tenant#charts"
  get "tasks_report", to: "tenant#tasks_report"

  resources :clients do
    resources :comments
  end
  resources :payments
  resources :tasks do
    member do
      patch :change_status
    end
    resources :comments
  end
  resources :projects do
    member do
      patch :change_status
    end
  end
  resources :tags
  resources :cash_accounts
end

app/models/project.rb
class Project < ApplicationRecord
  acts_as_tenant(:tenant)
  belongs_to :client
  has_many :taggings, as: :taggable, dependent: :destroy
  has_many :tags, through: :taggings
  has_many :tasks, dependent: :restrict_with_error, counter_cache: true

  validates :client, :payment_type, :name, presence: true

  monetize :price, as: :price_cents

  PAYMENT_TYPES = [:hourly, :fixed]
  def self.payment_types
    PAYMENT_TYPES.map { |payment_type| [payment_type, payment_type] }
  end

  STATUSES = %w[active archived]
  validates :status, inclusion: {in: STATUSES, message: "%{value} is not available."}
  def self.statuses
    STATUSES.map { |status| [status, status] }
  end

  def to_s
    name
  end

  include PublicActivity::Model
  tracked owner: proc { |controller, model| controller.current_user }
  tracked tenant_id: proc { ActsAsTenant.current_tenant.id }

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  include SetTenant # include ON TOP of controller that has to be scoped
  include RequireTenant # no current_tenant = no access to entire controller. redirect to root
  include SetCurrentMember # for role-based authorization. @current_member.admin?
  include RequireActiveSubscription # no access unless tenant has an active subscription

  before_action :set_project, only: %w[show edit update destroy change_status]

  def index
    @q = Project.ransack(params[:q])
    @pagy, @projects = pagy(@q.result.includes(:client).order("projects.created_at DESC"))
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "Projects",
               orientation: "Portrait",
               page_size: "A4",
               template: "projects/project.pdf.erb"
      end
    end
  end

  def change_status
    if params[:status].present? && Project::STATUSES.include?(params[:status])
      @project.update(status: params[:status])
    end
    redirect_to @project, notice: "Status updated to #{@project.status}"
  end

  def show
  end

  def new
    @project = Project.new
    @clients = Client.all
  end

  def edit
    @clients = Client.all
  end

  def create
    @project = Project.new(project_params)

    if @project.save
      redirect_to @project, notice: 'Project was successfully created.'
    else
      @clients = Client.all
      render :new
    end
  end

  def update
    if @project.update(project_params)
      redirect_to @project, notice: 'Project was successfully updated.'
    else
      @clients = Client.all
      render :edit
    end
  end

  def destroy
    if @project.destroy
      redirect_to projects_url, notice: 'Project was successfully destroyed.'
    else
      redirect_to projects_url, alert: 'Project has associations. Can not be destroyed.'
    end
  end

  private
    def set_project
      @project = Project.find(params[:id])
    end

    def project_params
      params.require(:project).permit(:name, :description, :client_id, 
        :payment_type, :price, :price_cents, tag_ids: [])
    end
end

app/views/projects/_form.html.erb
<%= simple_form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <ul class="text-danger">
      <% @project.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  <% end %>

  <div class="form-inputs">
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.label :client %>
    <%= f.select :client_id, @clients.map{|c| [c.name, c.id]}, {include_blank: true}, class: 'selectize' %>
    <%= f.error :client, class: "text-danger" %>
    <%= f.input :payment_type, collection: Project.payment_types %>
    <%= f.input :price_cents %>
    <%= f.label :tags %>
    <%= f.select :tag_ids, Tag.where(category: "project").pluck(:name, :id), {}, { multiple: true, class: "selectize" } %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<% model_class = Project %>
<div class="card shadow">
  <div class="card-header">
    <h4>
      <%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %>
      Project
    </h4>
  </div>
  <div class="card-body">
    <%= render 'form', project: @project %>
  </div>
  <div class="card-footer">
    <%= link_to t(".back", default: t("helpers.links.back")).capitalize, @project, class: "btn btn-sm btn-secondary" %>
  </div>
</div>

app/views/projects/index.html.erb
<% model_class = Project %>
<h3>
  <div class="text-center">
    Projects
    <div class="badge bg-info">
      <%= @projects.count %>
    </div>
    <%= link_to t('.new', default: t("helpers.links.new")), new_project_path, class: 'btn btn-primary' %>
    <%= link_to "PDF", projects_path(format: :pdf), class: 'btn btn-danger' %>
    <!-- Button trigger modal -->
    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
      <i class="fa fa-search"></i>
      Search
    </button>
    <% if params.has_key?(:q) %>
      <%= link_to "Unfilter", projects_path, class: "btn btn-secondary" %>
    <% end %>
  </div>
</h3>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Search</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <%= search_form_for @q, url: projects_path do |f| %>
          <%= model_class.human_attribute_name(:client) %>
          <%= f.select :client_name_cont, Client.all.map{|c| [c.name, c.name]}, {include_blank: Client.all.length > 1}, class: 'selectize' %>
          <%= model_class.human_attribute_name(:name) %>
          <%= f.search_field :name_cont, class: "form-control" %>
          <%= model_class.human_attribute_name(:status) %>
          <%= f.select :status_eq, Project.statuses, {:include_blank => true}, :class => "form-control" %>
          <br>
          <%= f.button :submit, class: "btn btn-primary btn-block" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<hr>
<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover table-sm table-light shadow">
    <thead>
      <tr>
        <th><%= sort_link(@q, :id) %></th>
        <th><%= sort_link(@q, :name) %></th>
        <th>Description</th>
        <th>Client</th>
        <th><%= sort_link(@q, :payment_type) %></th>
        <th>Price</th>
        <th><%= sort_link(@q, :tasks_count) %></th>
        <th><%= sort_link(@q, :status) %></th>
        <th>Tags</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @projects.each do |project| %>
        <%= content_tag :tr, id: dom_id(project), class: dom_class(project) do %>
          <td><%= link_to project.id, project %></td>
            <td><%= project.name %></td>
            <td><%= project.description %></td>
            <td><%= link_to project.client, project.client %></td>
            <td><%= project.payment_type %></td>
            <td><%= project.price %></td>
            <td><%= project.tasks_count %></td>
            <td><%= project.status %></td>
            <td><%= render 'tags/tags', model: project %></td>
          <td>
            <%= link_to t(".edit", default: t("helpers.links.edit")).capitalize, edit_project_path(project), class: 'btn btn-sm btn-warning' %>
            <%= link_to t(".destroy", default: t("helpers.links.destroy")).capitalize, project, method: :delete, data: { confirm: t('.confirm', default: t("helpers.links.confirm", default: 'Are you sure?')) }, class: 'btn btn-sm btn-danger' %>
          </td>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/projects/new.html.erb
<% model_class = Project %>
<div class="card shadow">
  <div class="card-header">
    <h4>
      <%=t '.title', :default => [:'helpers.titles.new', 'Create %{model}'], :model => model_class.model_name.human.titleize %>
      Project
    </h4>
  </div>
  <div class="card-body">
    <%= render 'form', project: @project %>
  </div>
  <div class="card-footer">
    <%= link_to t(".back", default: t("helpers.links.back")).capitalize, projects_path, class: "btn btn-sm btn-secondary" %>
  </div>
</div>

app/views/projects/project.pdf.erb
A PDF

<%= Date.today %>
<%= @projects.count %>
<table style="width:100%">
  <thead>
    <tr>
      <th>id
      <th>name
      <th>Description</th>
      <th>Client</th>
      <th>payment_type
      <th>Price</th>
      <th>tasks_count
      <th>status
      <th>Tags</th>
    </tr>
  </thead>
  <tbody>
    <% @projects.each do |project| %>
      <%= content_tag :tr, id: dom_id(project), class: dom_class(project) do %>
        <td><%= project.id %></td>
        <td><%= project.name %></td>
        <td><%= project.description %></td>
        <td><%= project.client %></td>
        <td><%= project.payment_type %></td>
        <td><%= project.price %></td>
        <td><%= project.tasks_count %></td>
        <td><%= project.status %></td>
        <td><%= project.tags.pluck(:name) %></td>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/projects/show.html.erb
<% model_class = Project %>
<div class="card shadow">
  <div class="card-header">
    <h4>
      Project
    </h4>
  </div>
  <div class="card-body">
  
    <b>Name:</b>
    <%= @project.name %>
    <br>
  
    <b>Description:</b>
    <%= @project.description %>
    <br>
  
    <b>Client:</b>
    <%= link_to @project.client, @project.client %>
    <br>
  
    <b>Payment type:</b>
    <%= @project.payment_type %>
    <br>
  
    <b>Price:</b>
    <%= @project.price_cents %>
    <br>

    <b>Tasks Count:</b>
    <%= @project.tasks_count %>
    <br>

    <b>Status:</b>
    <%= @project.status %>
    <br>

    <b>Tags:</b>
    <%= render 'tags/tags', model: @project %>
    <br>
  
  </div>
  <div class="card-footer">
    <div class="btn-group">
      <% Project::STATUSES.each do |status| %>
        <%= link_to change_status_project_path(@project, status: status), method: :patch, class: "btn btn-sm btn-info #{'disabled' if @project.status == status}" do %>
          <%= status %>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="card-footer">
    <%= link_to t(".edit", default: t("helpers.links.edit")).capitalize, edit_project_path(@project), class: "btn btn-sm btn-warning" %>
    <%= link_to t(".destroy", default: t("helpers.links.destroy")).capitalize, @project, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-danger" %>
    <%= link_to t(".back", default: t("helpers.links.back")).capitalize, projects_path, class: "btn btn-sm btn-secondary" %>
  </div>
</div>