config/routes.rb
Rails.application.routes.draw do
  match "/404", via: :all, to: "errors#not_found"
  match "/500", via: :all, to: "errors#internal_server_error"

  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  get "telegram_auth", to: "telegram#telegram_auth"
  post "telegram_auth", to: "telegram#telegram_auth"
  post "telegram/send_reminder/:id", to: "telegram#send_reminder", as: :send_reminder
  # works same as above
  # post "telegram/:id/send_reminder", to: "telegram#send_reminder", as: :send_reminder

  root "static_public#landing_page"
  get "about", to: "static_public#about"
  get "pricing", to: "static_public#pricing"
  get "privacy", to: "static_public#privacy"
  get "terms", to: "static_public#terms"

  authenticated :user, lambda { |u| u.superadmin? } do
    scope :superadmin, as: "superadmin" do
      root "superadmin#users"
      get "tenants", to: "superadmin#tenants"
      get "users", to: "superadmin#users"
    end
  end

  resources :users, only: [:show] do
    member do
      patch :resend_invitation
    end
  end

  resources :tenants do
    member do
      patch :switch
    end
  end

  # stripe
  post "checkout", to: "checkout#create"
  get "checkout/success", to: "checkout#success"
  get "checkout/failure", to: "checkout#failure"
  post "billing_portal", to: "billing_portal#create"
  post "webhooks", to: "webhooks#create"

  resources :members, except: [:create, :new] do
    get :invite, on: :collection
  end

  get "dashboard", to: "tenant#dashboard"
  get "calendar", to: "tenant#calendar"
  get "activity", to: "tenant#activity"
  get "charts", to: "tenant#charts"
  get "tasks_report", to: "tenant#tasks_report"

  resources :clients do
    resources :comments
  end
  resources :payments
  resources :tasks do
    member do
      patch :change_status
    end
    resources :comments
  end
  resources :projects do
    member do
      patch :change_status
    end
  end
  resources :tags
  resources :cash_accounts
end

app/models/tag.rb
class Tag < ApplicationRecord
  acts_as_tenant(:tenant)
  validates :name, :category, presence: true
	validates :name, length: {minimum: 1, maximum: 25}, uniqueness: { scope: :category, message: "uniquene per category" }
  
  def to_s
    name
  end

  CATEGORIES = [:client, :payment, :task, :project]
  def self.categories
    CATEGORIES.map { |category| [category, category] }
  end

	has_many :taggings, dependent: :destroy

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  include SetTenant # include ON TOP of controller that has to be scoped
  include RequireTenant # no current_tenant = no access to entire controller. redirect to root
  include SetCurrentMember # for role-based authorization. @current_member.admin?
  include RequireActiveSubscription # no access unless tenant has an active subscription

  before_action :set_tag, only: [:show, :edit, :update, :destroy]

  def index
    @tags = Tag.all.order(created_at: :desc)
  end

  def show
  end

  def new
    @tag = Tag.new
  end

  def edit
  end

  def create
    @tag = Tag.new(tag_params)

    if @tag.save
      redirect_to @tag, notice: 'Tag was successfully created.'
    else
      render :new
    end
  end

  def update
    if @tag.update(tag_params)
      redirect_to @tag, notice: 'Tag was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @tag.destroy
    redirect_to tags_url, notice: 'Tag was successfully destroyed.'
  end

  private
    def set_tag
      @tag = Tag.find(params[:id])
    end

    def tag_params
      params.require(:tag).permit(:name, :category)
    end
end

app/views/tags/_form.html.erb
<%= simple_form_for(@tag) do |f| %>
  <% if @tag.errors.any? %>
    <ul class="text-danger">
      <% @tag.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  <% end %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :category, collection: Tag.categories %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/tags/_tags.html.erb
<% model.tags.each do |tag| %>
  <div class="badge bg-info">
    <%= tag.name %>
  </div>
<% end %>

app/views/tags/edit.html.erb
<% model_class = Tag %>
<div class="card shadow">
  <div class="card-header">
    <h4>
      <%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %>
      Tag
    </h4>
  </div>
  <div class="card-body">
    <%= render 'form', tag: @tag %>
  </div>
  <div class="card-footer">
    <%= link_to t(".back", default: t("helpers.links.back")).capitalize, @tag, class: "btn btn-sm btn-secondary" %>
  </div>
</div>

app/views/tags/index.html.erb
<h3>
  <div class="text-center">
    Tags
    <div class="badge bg-info">
      <%= @tags.count %>
    </div>
    <%= link_to t('.new', default: t("helpers.links.new")), new_tag_path, class: 'btn btn-primary' %>
  </div>
</h3>
<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover table-sm table-light shadow">
    <thead>
      <tr>
        <th>Id</th>
    	  
        <th>Name</th>
        
        <th>category</th>
        
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @tags.each do |tag| %>
        <%= content_tag :tr, id: dom_id(tag), class: dom_class(tag) do %>
          <td><%= link_to tag.id, tag %></td>
          
            <td><%= tag.name %></td>
          
            <td><%= tag.category %></td>
          
          <td>
            <%= link_to t(".edit", default: t("helpers.links.edit")).capitalize, edit_tag_path(tag), class: 'btn btn-sm btn-warning' %>
            <%= link_to t(".destroy", default: t("helpers.links.destroy")).capitalize, tag, method: :delete, data: { confirm: t('.confirm', default: t("helpers.links.confirm", default: 'Are you sure?')) }, class: 'btn btn-sm btn-danger' %>
          </td>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/tags/new.html.erb
<% model_class = Tag %>
<div class="card shadow">
  <div class="card-header">
    <h4>
      <%=t '.title', :default => [:'helpers.titles.new', 'Create %{model}'], :model => model_class.model_name.human.titleize %>
      Tag
    </h4>
  </div>
  <div class="card-body">
    <%= render 'form', tag: @tag %>
  </div>
  <div class="card-footer">
    <%= link_to t(".back", default: t("helpers.links.back")).capitalize, tags_path, class: "btn btn-sm btn-secondary" %>
  </div>
</div>

app/views/tags/show.html.erb
<% model_class = Tag %>
<div class="card shadow">
  <div class="card-header">
    <h4>
      Tag
    </h4>
  </div>
  <div class="card-body">
  
    <b>Name:</b>
    <%= @tag.name %>
    <br>
  
    <b>category:</b>
    <%= @tag.category %>
    <br>
  
  </div>
  <div class="card-footer">
    <%= link_to t(".edit", default: t("helpers.links.edit")).capitalize, edit_tag_path(@tag), class: "btn btn-sm btn-warning" %>
    <%= link_to t(".destroy", default: t("helpers.links.destroy")).capitalize, @tag, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-danger" %>
    <%= link_to t(".back", default: t("helpers.links.back")).capitalize, tags_path, class: "btn btn-sm btn-secondary" %>
  </div>
</div>