config/routes.rb
Rails.application.routes.draw do
  match "/404", via: :all, to: "errors#not_found"
  match "/500", via: :all, to: "errors#internal_server_error"

  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  get "telegram_auth", to: "telegram#telegram_auth"
  post "telegram_auth", to: "telegram#telegram_auth"
  post "telegram/send_reminder/:id", to: "telegram#send_reminder", as: :send_reminder
  # works same as above
  # post "telegram/:id/send_reminder", to: "telegram#send_reminder", as: :send_reminder

  root "static_public#landing_page"
  get "about", to: "static_public#about"
  get "pricing", to: "static_public#pricing"
  get "privacy", to: "static_public#privacy"
  get "terms", to: "static_public#terms"

  authenticated :user, lambda { |u| u.superadmin? } do
    scope :superadmin, as: "superadmin" do
      root "superadmin#users"
      get "tenants", to: "superadmin#tenants"
      get "users", to: "superadmin#users"
    end
  end

  resources :users, only: [:show] do
    member do
      patch :resend_invitation
    end
  end

  resources :tenants do
    member do
      patch :switch
    end
  end

  # stripe
  post "checkout", to: "checkout#create"
  get "checkout/success", to: "checkout#success"
  get "checkout/failure", to: "checkout#failure"
  post "billing_portal", to: "billing_portal#create"
  post "webhooks", to: "webhooks#create"

  resources :members, except: [:create, :new] do
    get :invite, on: :collection
  end

  get "dashboard", to: "tenant#dashboard"
  get "calendar", to: "tenant#calendar"
  get "activity", to: "tenant#activity"
  get "charts", to: "tenant#charts"
  get "tasks_report", to: "tenant#tasks_report"

  resources :clients do
    resources :comments
  end
  resources :payments
  resources :tasks do
    member do
      patch :change_status
    end
    resources :comments
  end
  resources :projects do
    member do
      patch :change_status
    end
  end
  resources :tags
  resources :cash_accounts
end

app/models/payment.rb
class Payment < ApplicationRecord
  acts_as_tenant(:tenant)
  belongs_to :payable, polymorphic: true, touch: true, counter_cache: true
  belongs_to :cash_account, touch: true, counter_cache: true
  validates :amount, presence: true

  def to_s
    [payable_type, payable_id].join(" ")
  end

  monetize :amount, as: :amount_cents

  include PublicActivity::Model
  tracked owner: proc { |controller, model| controller.current_user }
  tracked tenant_id: proc { ActsAsTenant.current_tenant.id }

  has_many :taggings, as: :taggable, dependent: :destroy
  has_many :tags, through: :taggings

end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  include SetTenant # include ON TOP of controller that has to be scoped
  include RequireTenant # no current_tenant = no access to entire controller. redirect to root
  include SetCurrentMember # for role-based authorization. @current_member.admin?
  include RequireActiveSubscription # no access unless tenant has an active subscription

  before_action :set_payment, only: [:show, :edit, :update, :destroy]

  def index
    @pagy, @payments = pagy(Payment.all)
  end

  def show
  end

  def new
    @payment = Payment.new
  end

  def edit
  end

  def create
    @payment = Payment.new(payment_params)

    if @payment.save
      redirect_to @payment, notice: 'Payment was successfully created.'
    else
      render :new
    end
  end

  def update
    if @payment.update(payment_params)
      redirect_to @payment, notice: 'Payment was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @payment.destroy
    redirect_to payments_url, notice: 'Payment was successfully destroyed.'
  end

  private
    def set_payment
      @payment = Payment.find(params[:id])
    end

    def payment_params
      params.require(:payment).permit(:payable_id, :payable_type, :amount,
        :description, :amount_cents, :cash_account_id, tag_ids: [])
    end
end

app/views/payments/_form.html.erb
<%= simple_form_for(@payment) do |f| %>
  <% if @payment.errors.any? %>
    <ul class="text-danger">
      <% @payment.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  <% end %>

  <div class="form-inputs">
    <%= f.association :cash_account %>
    <%= f.input :payable_type, input_html: {value: @payment.payable_type || params[:payable_type]}, as: :hidden %>
    <% if @payment.payable_type.present? %>
    <%= f.input :payable_id, collection: @payment.payable_type.classify.constantize.all %>
    <% elsif params[:payable_type].present? %>
    <%= f.input :payable_id, collection: params[:payable_type].classify.constantize.all %>
    <% end %>
    <%= f.input :amount_cents %>
    <%= f.input :description %>
    <%= f.label :tags %>
    <%= f.select :tag_ids, Tag.where(category: "payment").pluck(:name, :id), {}, { multiple: true, class: "selectize" } %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/payments/edit.html.erb
<% model_class = Payment %>
<div class="card shadow">
  <div class="card-header">
    <h4>
      <%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %>
      Payment
    </h4>
  </div>
  <div class="card-body">
    <%= render 'form', payment: @payment %>
  </div>
  <div class="card-footer">
    <%= link_to t(".back", default: t("helpers.links.back")).capitalize, @payment, class: "btn btn-sm btn-secondary" %>
  </div>
</div>

app/views/payments/index.html.erb
<h3>
  <div class="text-center">
    Payments
    <div class="badge bg-info">
      <%= @payments.count %>
    </div>
    <%= link_to "Client Payment", new_payment_path(payable_type: "Client"), class: 'btn btn-primary' %>
    <%= link_to "Member Payment", new_payment_path(payable_type: "Member"), class: 'btn btn-primary' %>
  </div>
</h3>
<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover table-sm table-light shadow">
    <thead>
      <tr>
        <th>Id</th>
    	  
        <th>CashAccount</th>
        <th>Payable</th>
        
        <th>Amount</th>
        
        <th>Description</th>
        <th>Tags</th>
        
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @payments.each do |payment| %>
        <%= content_tag :tr, id: dom_id(payment), class: dom_class(payment) do %>
          <td><%= link_to payment.id, payment %></td>
          
            <td><%= link_to payment.cash_account, payment.cash_account %></td>
            <td><%= link_to payment.payable, payment.payable %></td>
          
            <td><%= payment.amount_cents %></td>
          
            <td><%= payment.description %></td>
            <td><%= render 'tags/tags', model: payment %></td>
          
          <td>
            <%= link_to t(".edit", default: t("helpers.links.edit")).capitalize, edit_payment_path(payment), class: 'btn btn-sm btn-warning' %>
            <%= link_to t(".destroy", default: t("helpers.links.destroy")).capitalize, payment, method: :delete, data: { confirm: t('.confirm', default: t("helpers.links.confirm", default: 'Are you sure?')) }, class: 'btn btn-sm btn-danger' %>
          </td>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>
<%== pagy_bootstrap_nav(@pagy) %>

app/views/payments/new.html.erb
<% model_class = Payment %>
<div class="card shadow">
  <div class="card-header">
    <h4>
      <%=t '.title', :default => [:'helpers.titles.new', 'Create %{model}'], :model => model_class.model_name.human.titleize %>
      Payment
    </h4>
  </div>
  <div class="card-body">
    <%= render 'form', payment: @payment %>
  </div>
  <div class="card-footer">
    <%= link_to t(".back", default: t("helpers.links.back")).capitalize, payments_path, class: "btn btn-sm btn-secondary" %>
  </div>
</div>

app/views/payments/show.html.erb
<% model_class = Payment %>
<div class="card shadow">
  <div class="card-header">
    <h4>
      Payment
    </h4>
  </div>
  <div class="card-body">
  
    <b>Payable:</b>
    <%= link_to @payment.payable, @payment.payable %>
    <br>
  
    <b>Amount:</b>
    <%= @payment.amount_cents %>
    <br>

    <b>CashAccount:</b>
    <%= link_to @payment.cash_account, @payment.cash_account %>
    <br>
  
    <b>Description:</b>
    <%= @payment.description %>
    <br>

    <b>Tags:</b>
    <%= render 'tags/tags', model: @payment %>
    <br>
  
  </div>
  <div class="card-footer">
    <%= link_to t(".edit", default: t("helpers.links.edit")).capitalize, edit_payment_path(@payment), class: "btn btn-sm btn-warning" %>
    <%= link_to t(".destroy", default: t("helpers.links.destroy")).capitalize, @payment, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-danger" %>
    <%= link_to t(".back", default: t("helpers.links.back")).capitalize, payments_path, class: "btn btn-sm btn-secondary" %>
  </div>
</div>